### ISSUE TITLE
Documentation Request (Data + Project set up)

### ISSUE THREAD

**Issue by david-roper** [Rodent-Cognition-Core/CBAS#40]
I am a developer working with the Douglas Mental Health University Institute, partnered with Western University on the TRIDENT project. We are looking into setting up Mousebytes and be able to contribute our mouse Touchscreen data to the database. Documentation on how to set up the project as well as what types and format of data that can be uploaded to the site would be much appreciated. Thanks!

**Comment by Rodent-Cognition-Core** [comment]
@david-roper Super excited to help you contribute your data to Mousebytes, to clarify Mousebytes contains touchscreen data (XML file type) exported from ABET. Where as MouseBytes+ allows you to share any data type associated with the touchscreen project (i.e mp4, csv, neural data). To get started have a look at the [guideline](https://mousebytes.ca/guideline) and [video ](https://mousebytes.ca/video-tutorial) tutorials found on the website. If you any questions or concern don't hesitate to reach out: [mousebytes@uwo.ca](mailto:mousebytes@uwo.ca)

**Comment by Rodent-Cognition-Core** [comment]
Closed due to inactivity
